import type { Metadata } from "next";
// 1. Noto Sans JPをインポート
import {Dela_Gothic_One } from "next/font/google";
import "./globals.css";

// 2. フォントを設定（太さやサブセットなどを指定）
const delaGothicOne = Dela_Gothic_One({
  subsets: ["latin"],
  weight: "400", 
  display: "swap", // フォント読み込み中のちらつきを防止
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 3. classNameをhtmlタグに適用
    <html lang="ja" className={delaGothicOne.className}>
      <body>{children}</body>
    </html>
  );
}